config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins

  namespace :manager do
    resources :yarns
    resources :admins
    resources :users
    resources :designs
    resources :retailers
    resources :leads
    resources :catalogs

    root to: "admins#index"
  end

  resources :main

	resources :retailers
	resources :designs
  resources :leads
  resources :catalogs
  resources :yarns

	root 'main#leads'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable,
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/catalog.rb
class Catalog < ApplicationRecord
	has_one_attached :catalog_pdf
end

app/models/design.rb
class Design < ApplicationRecord
	has_and_belongs_to_many :yarns

	has_one_attached :main_image
	has_one_attached :pattern

	scope :by_yarn, -> (yarn) { joins(:yarns).where(yarns: {name: yarn}) }
end

app/models/lead.rb
class Lead < ApplicationRecord
	validates :company_name, :contact, :email, presence: true
	validates :email, uniqueness: { case_sensitive: false }

	before_save :downcase_email

	def downcase_email
		self.email.downcase!
	end
end

app/models/retailer.rb
class Retailer < ApplicationRecord
	has_and_belongs_to_many :yarns

	def has_some_yarns_for_design(design)
		# Is the intersection non-empty?
		(design.yarns.length - (design.yarns - yarns).length) > 0
	end

	def has_all_yarns_for_design(design)
		#Is the design.yarns a subset of the retailer.yarns?
		(design.yarns - yarns).empty?
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :registerable,
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/yarn.rb
class Yarn < ApplicationRecord
  has_and_belongs_to_many :designs
  has_and_belongs_to_many :retailers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def index
  	@catalogs = Catalog.all
  end
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :authenticate_admin!, except: [ :show, :index ]

  def index
		@designs = Design.with_attached_main_image.where(nil)
    @designs = @designs.by_yarn(params[:yarn]) if params[:yarn].present?
	end

	def show
		@design = Design.find(params[:id])
	end

  def new
  	@design = Design.new
  end

  def create
  	@design = Design.new(design_params)

  	if @design.save
  		redirect_to @design
  	else
  		render 'new'
  	end
  end

  def destroy
		@design = Design.find(params[:id])
		@design.main_image.purge
		@design.destroy

		redirect_to designs_path
	end

  private
		def design_params
			params.require(:design).permit(:main_image, :name, :description)
		end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
	def create
		@lead = Lead.new(lead_params)

		if @lead.save
			flash[:notice] = "Du er påmeldt!"
			redirect_to root_path
		else
			render 'main/leads'
		end
	end

  private
  	def lead_params
  		params.require(:lead).permit(:email, :contact, :company_name)
  	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def leads
  	@lead = Lead.new
  end


end

app/controllers/manager/designs_controller.rb
module Manager
  class DesignsController < Manager::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Design.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Design.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/manager/leads_controller.rb
module Manager
  class LeadsController < Manager::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Lead.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Lead.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/manager/users_controller.rb
module Manager
  class UsersController < Manager::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
	before_action :authenticate_admin!, except: [ :show, :index ]


	def index
		@retailers = Retailer.order(:name)
	end

	def show
		@retailer = Retailer.find(params[:id])
	end

	def new
		@retailer = Retailer.new
	end

	def edit
		@retailer = Retailer.find(params[:id])
	end

	def update
		@retailer = Retailer.find(params[:id])

		if @retailer.update(retailer_params)
			redirect_to @retailer
		else
			render 'edit'
		end
	end

	def create
		@retailer = Retailer.new(retailer_params)

		if @retailer.save
			redirect_to @retailer
		else
			render 'new'
		end
	end

	def destroy
		@retailer = Retailer.find(params[:id])
		@retailer.destroy

		redirect_to retailers_path
	end

	private
		def retailer_params
			params.require(:retailer).permit(:description, :name, :website, :street_address, :post_code, :post_area)
		end
end

app/controllers/yarns_controller.rb
class YarnsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
	def can_download_pattern?
		user_signed_in?
	end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/yarns_helper.rb
module YarnsHelper
end

app/views/designs/_form.html.erb
<%= form_for @design do |f| %>
	
	<%= render 'shared/error_messages', object: f.object %>

	<div>
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>

	<div>
		<%= f.label :description %>
		<%= f.text_area :description, :class => "tinymce" %>

		<%= tinymce %>
	</div>

	<div>
		<%= f.label :main_image %>
		<%= f.file_field :main_image, class: "form-control" %>
	</div>



	<%= f.submit "OK" %>

<% end %> 

app/views/designs/index.html.erb
<% @designs.in_groups_of(3).each do |group| %>
	<div class="row">
	<% group.each do |item| %>
	<div class="col-sm-4">
		<% if item %>
			<div class="panel panel-default">
				<div class="panel-heading">
					<%= item.name %>
				</div>
				<div class="panel-body">
					<% if item.main_image.attached? %>
						<%= link_to item do %>
							<%= image_tag item.main_image.variant(resize: "400x600"), class: "img-responsive w-100" %>
						<% end %>
					<% end %>
				</div>
				<div class="panel-footer">
				<ul class="yarns">
					<% item.yarns.pluck(:name).each do |yarn| %>
						<li><%= yarn %></li>
					<% end %>
				</ul>
				<% if can_download_pattern? %>
					<% if item.pattern.attached? %>
							<%= link_to("Last ned oppskrift", rails_blob_path(item.pattern, disposition: "attachment")) %>
					<% end %>
				<% end %>
				</div>
			</div>
		<% end %>
	</div>
	<% end %>
	</div>

<% end %>

app/views/designs/new.html.erb
<h1>New design</h1>

<%= render 'form' %>

app/views/designs/show.html.erb
<div class="row">
	<div class="col-md-6">
		<% if @design.main_image.attached? %>
			<%= image_tag @design.main_image.variant(resize: "800X600") %>
		<% end %>
	</div>
	<div class="col-md-6">
		<h3> <%= @design.name %> </h3>
		<p>
			<%= sanitize(@design.description) %>
		</p>
		<ul class="yarns">
			<% @design.yarns.pluck(:name, :id).each do |yarn, id| %>
				<%= link_to yarn_path(id) do %>
					<li><%= yarn %></li>
				<% end %>
			<% end %>
		</ul>
	</div>

</div>






<% if can_download_pattern? %>
	<% if @design.pattern.attached? %>
		<div>
			<%= link_to(image_tag(@design.pattern.preview(resize: "200x200")), rails_blob_path(@design.pattern, disposition: "attachment")) %>
		</div>
	<% end %>
<% end %>